/* A packrat parser generated by PackCC 1.2.0 */

#ifndef PCC_INCLUDED__EXPR_H
#define PCC_INCLUDED__EXPR_H



//	include "ast.h"




#include "ast.h"

static idents_t* Idents;






#ifdef __cplusplus
extern "C" {
#endif

typedef struct expr_context_tag expr_context_t;

expr_context_t *expr_create(parser_t*auxil);
int expr_parse(expr_context_t *ctx, asn_t**ret);
void expr_destroy(expr_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__EXPR_H */
