/* A packrat parser generated by PackCC 1.2.0 */

#ifndef PCC_INCLUDED__LC_H
#define PCC_INCLUDED__LC_H

char * strdup(const char *);
#include <string.h>

#include "ast.h"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct lc_context_tag lc_context_t;

lc_context_t *lc_create(parser_t*auxil);
int lc_parse(lc_context_t *ctx, ast_node_t *ret);
void lc_destroy(lc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__LC_H */
