/* A packrat parser generated by PackCC 1.2.0 */

#ifndef PCC_INCLUDED__LC_LUA_H
#define PCC_INCLUDED__LC_LUA_H

    char * strdup(const char *);
    #include <string.h>
    #include <stdio.h>
    #include <stdlib.h>
    #include <getopt.h>

    #include "scope.h"

    typedef struct {
            lua_State* L;
            FILE* input;
            const char * file_name;
            int lines_count;
            int pos;
            int level;
            int ctx;
            scope_t* scope;
            idents_t* idents;
            int lines[2048];
    } parser_t;
    //# include "ast.h"
    int pcc_getchar(parser_t* p){ 
            int c;
            while( (c = fgetc(p->input))=='\r' );
            p->pos += 1;
            if(c=='\n'){ p->lines[p->lines_count++] = p->pos; }
            return c; 
    }

#define PCC_GETCHAR(auxil) pcc_getchar(auxil)


#ifdef __cplusplus
extern "C" {
#endif

typedef struct lc_context_tag lc_context_t;

lc_context_t *lc_create(parser_t*auxil);
int lc_parse(lc_context_t *ctx, int *ret);
void lc_destroy(lc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__LC_LUA_H */
